export const fakeData = {
  mobile: {
    id: 'root',
    thumnail: '_',
    type: 'grid',
    columns: '1',
    gap: '1',
    rows: '1',
    colspan: '1',
    rowspan: '1',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    childs: [
      {
        colspan: '1',
        rowspan: '1',
        columns: '1',
        rows: '1',
        type: 'content',
        gap: '1',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        thumbnail: '',
        value: 'text',
        id: 'text$bzypsdyua9etkqy7a37z2s',
        childs: [],
      },
    ],
  },
  desktop: {
    id: 'root',
    thumnail: '_',
    type: 'grid',
    columns: '1',
    gap: '1',
    rows: '1',
    colspan: '1',
    rowspan: '1',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    childs: [
      {
        colspan: '4',
        rowspan: '1',
        columns: '1',
        rows: '1',
        type: 'flex',
        gap: '5',
        alignItems: 'flex-start',
        justifyContent: 'flex-start',
        thumbnail: '_',
        id: 'Box-b35cbfe3-1174-4468-94b3-3227da8f4aab',
        childs: [
          {
            colspan: '1',
            rowspan: '1',
            columns: '1',
            rows: '1',
            type: 'grid',
            gap: '2',
            alignItems: 'flex-start',
            justifyContent: 'flex-start',
            thumbnail: '_',
            id: 'Grid-3fde15c9-0123-4f19-a954-e8cc0fd439b6',
            childs: [
              {
                colspan: '1',
                rowspan: '1',
                columns: '1',
                rows: '1',
                type: 'content',
                gap: '1',
                alignItems: 'flex-start',
                justifyContent: 'flex-start',
                thumbnail: '',
                value: 'text',
                id: 'text$qw5xi9l8a1axcrspzn6t2e',
                childs: [],
                valueRender: {
                  jsonPath: '$[].title',
                  apiCall: {
                    id: 'ffe40194-265e-4181-ad91-d3785d46b09f',
                    name: 'Get comments',
                    method: 'GET',
                    url: 'https://jsonplaceholder.typicode.com/users/1/posts',
                  },
                },
                style_pc: {
                  after: {
                    color: '#333333',
                  },
                  backgroundColor: '#d4f7d8',
                  padding: '3px 3px 3px 3px',
                },
              },
              {
                colspan: '1',
                rowspan: '1',
                columns: '1',
                rows: '1',
                type: 'content',
                gap: '1',
                alignItems: 'flex-start',
                justifyContent: 'flex-start',
                thumbnail: '',
                value: 'description',
                id: 'description$hll7uukb3fribdx19bli79',
                childs: [],
                valueRender: {
                  jsonPath: '$[].body',
                  apiCall: {
                    id: 'ffe40194-265e-4181-ad91-d3785d46b09f',
                    name: 'Get comments',
                    method: 'GET',
                    url: 'https://jsonplaceholder.typicode.com/users/1/posts',
                  },
                },
                style_pc: {
                  before: {
                    color: '#333333',
                  },
                  backgroundColor: '#f1f7d4',
                  padding: '3px 3px 3px 3px',
                  color: '#333333',
                },
                dataSlice: {
                  title: 'têst',
                },
              },
            ],
            style_pc: {
              backgroundColor: '#ffffff',
              borderTopLeftRadius: '4px',
              borderTopRightRadius: '4px',
              borderBottomRightRadius: '4px',
              borderBottomLeftRadius: '4px',
              padding: '4px 4px 4px 4px',
            },
            valueRender: {
              jsonPath: '',
              apiCall: {
                id: 'ffe40194-265e-4181-ad91-d3785d46b09f',
                name: 'Get comments',
                method: 'GET',
                url: 'https://jsonplaceholder.typicode.com/users/1/posts',
              },
            },
          },
        ],
        dataSlice: {
          titles: {},
        },
        valueRender: {
          jsonPath: '',
          allowDynamicGenerate: true,
          apiCall: {
            id: 'ffe40194-265e-4181-ad91-d3785d46b09f',
            name: 'Get comments',
            method: 'GET',
            url: 'https://jsonplaceholder.typicode.com/users/1/posts',
          },
        },
      },
    ],
  },
};
